[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "taxtie"
version = "0.0.1"
dependencies = ["uvicorn", "starlette"]

[project.optional-dependencies]
dev = ["pytest"]
